package judge;

import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Nguyen Vuong Khang Hy 
 * Email: khanghy3004@gmail.com 
 * Automatic Judger
 */
public class frmProcess extends javax.swing.JFrame {
    frmJudge parent;
    /**
     * Creates new form frmProgress
     * @param parent
     */
    public frmProcess(frmJudge parent) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/btnjudge.png")));
        this.parent = parent;
    }

    public JProgressBar getPrgJudging() {
        return prgJudging;
    }

    public void setPrgJudging(JProgressBar prgJudging) {
        this.prgJudging = prgJudging;
    }

    public JLabel getTxtCompileRun() {
        return txtCompileRun;
    }

    public void setTxtCompileRun(JLabel txtCompileRun) {
        this.txtCompileRun = txtCompileRun;
    }

    public JLabel getTxtContent() {
        return txtContent;
    }

    public void setTxtContent(JLabel txtContent) {
        this.txtContent = txtContent;
    }

    public JLabel getTxtTime() {
        return txtTime;
    }

    public void setTxtTime(JLabel txtTime) {
        this.txtTime = txtTime;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContent = new javax.swing.JLabel();
        prgJudging = new javax.swing.JProgressBar();
        txtCompileRun = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();

        setTitle("Judging");
        setResizable(false);

        txtContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContent.setText(" ");

        txtCompileRun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCompileRun.setText(" ");

        txtTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnStop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stop.png"))); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prgJudging, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtContent)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompileRun)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(btnStop)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTime)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtContent)
                .addGap(18, 18, 18)
                .addComponent(prgJudging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompileRun)
                    .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        parent.judge.stop();
        parent.timer.stop();
        parent.btnJudge.setEnabled(true);
        parent.btnUpdateOnline.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStop;
    private javax.swing.JProgressBar prgJudging;
    private javax.swing.JLabel txtCompileRun;
    private javax.swing.JLabel txtContent;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
